name: Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r mysecond/requirements.txt

      - name: Build Docker image
        run: docker build -t my-flask-app my-flask-app

      - name: Start Minikube
        run: minikube start

      - name: Load Docker image into Minikube
        run: eval $(minikube docker-env) && docker tag my-flask-app:latest my-flask-app:latest && docker save my-flask-app:latest | (eval $(minikube docker-env) && docker load)

      - name: Apply Kubernetes deployment
        run: kubectl apply -f deployment.yaml

